import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from './Providers';
import Navbar from '@/components/Navbar';
import { Toaster } from '@/components/ui/sonner';
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground min-h-screen flex flex-col`}
      >
        <Providers>
          <header className="bg-primary text-primary-foreground p-4 shadow-md">
            <div className="max-w-7xl mx-auto flex items-center justify-between">
              <div className="flex items-center gap-3 pl-16">
                <Link href="/" className="cursor-pointer hover:scale-105 transition-transform">
                  <img 
                    src="/logo.png" 
                    alt="Veri Saha Logo" 
                    className="w-20 h-20 object-contain rounded-full drop-shadow-lg filter contrast-200 brightness-150 mt-1"
                    style={{ 
                      imageRendering: 'auto', 
                      pointerEvents: 'none',
                      userSelect: 'none',
                      WebkitUserSelect: 'none',
                      MozUserSelect: 'none',
                      msUserSelect: 'none'
                    }}
                  />
                </Link>
                <span className="text-xl font-semibold tracking-wide">
                  VERİ SAHA
                </span>
              </div>
              <div className="pr-16">
                <Navbar />
              </div>
            </div>
          </header>
          <main className="flex-grow">
            {children}
          </main>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
